[tool.poetry]
name = "ai-assistant"
version = "0.1.0"
description = "Local multimodal assistant"
authors = ["Bill <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.10"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
