version: "3.9"

services:
  assistant:
    build:
      context: .
    deploy: {}
    device_requests:
      - driver: nvidia
        count: all
        capabilities: [gpu]
    environment:
      - HF_HOME=/data/hf_cache
      - ULTRALYTICS_HOME=/data/ultralytics_cache
      - PIPER_VOICE_DIR=/data/piper_models
    devices:
      - /dev/snd                  # give container access to host mic/speakers
    volumes:
      - ./:/app                   # mount your local code into /app
      - /mnt/ai-data:/data        # external SSD/HDD mount (models, FAISS, Piper)
    ports:
      - "8000:8000"               # placeholder for FastAPI UI

